### ISSUE TITLE
addCodelistAttribute throws a error regarding class

### ISSUE THREAD

**Issue by daniellenewby** [OHDSI/PhenotypeR#130]
Trying to run PhenotypeR with codelists from json files so i need to get my cohorts from jsons:

```
cancer_concepts <- CDMConnector::readCohortSet(
  path = here::here("cohorts"))

cdm <- CDMConnector::generateCohortSet(
  cdm,
  cohortSet = cancer_concepts,
  name = "outcome",
  overwrite = TRUE)
```

Then i need to carry out the function to add the codelist attributes.
```
cdm$outcome <- PhenotypeR::addCodelistAttribute(cohort = cdm$outcome, 
                                                codelist = list("all_lung_cancer_end" = 1L,
                                                                "broad_lung_cancer_end" = 1L,
                                                                "narrow_lung_cancer_end" = 1L,
                                                                "small_cell_lung_cancer" = 1L))
```

Error in `addCodelistAttribute()`:
✖ `cohort` must have class <cohort_table/cdm_table> but has class`cohort`
  <GeneratedCohortSet/tbl_PqConnection/tbl_dbi/tbl_sql/tbl_lazy/tbl>.
! `cohort` must be an object with class: <cohort_table/cdm_table>; it can contain extra classes; it can
  not be NULL.
---
Backtrace:
    ▆
 1. └─PhenotypeR::addCodelistAttribute(cohort = cdm$outcome, codelist = list(cohort_1 = 1L))
 2.   └─omopgenerics::validateCohortArgument(cohort = cohort)
 3.     └─omopgenerics::assertClass(...)
 4.       └─omopgenerics:::errorMessage(...)
 5.         └─cli::cli_abort(message = message, call = call)
 6.           └─rlang::abort(...)

The argument was working in a previous version of phenotypeR on github. When you try and run the examples for this function too you get the same error (see screenshot with red on bottom RHS)

![image](https://github.com/user-attachments/assets/1fa9ac73-abdf-488f-917f-b76ba6ad0ee9)

**Comment by edward-burn** [comment]
hmmm not sure, the example at least is working for me. Can you see if the below works for you (loading duckdb as it is needed for the IncidencePrevalence mock)

``` r
library(duckdb)
#> Loading required package: DBI
#> Warning: package 'DBI' was built under R version 4.4.1
library(IncidencePrevalence)
#> Warning: package 'IncidencePrevalence' was built under R version 4.4.2
library(PhenotypeR)

packageVersion("omopgenerics")
#> [1] '0.3.1'
packageVersion("CDMConnector")
#> [1] '1.5.0'
cdm <- mockIncidencePrevalenceRef(sampleSize = 1000)
cohort <- addCodelistAttribute(cohort = cdm$outcome, 
                               codelist = list("cohort_1" = 1L))
CDMConnector::cdm_disconnect(cdm)
```

<sup>Created on 2024-11-16 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by edward-burn** [comment]
@daniellenewby can we close this?

**Comment by daniellenewby** [comment]
error now resolved - thanks!
