### ISSUE TITLE
large scale characteristics order by descending values in cohort diagnostics tab in shiny

### ISSUE THREAD

**Issue by daniellenewby** [OHDSI/PhenotypeR#154]
In large scale characteristics in cohortdiagnostis tab. It would be useful to have the results ordered so that the a user can see them without having to order by count or percentage themselves? 

![image](https://github.com/user-attachments/assets/a155e4ba-ff31-46f8-bc62-7f523c0c17cb)

**Comment by edward-burn** [comment]
makes sense! opened a pr to do this
