### ISSUE TITLE
consider renaming the package before first release

### ISSUE THREAD

**Issue by catalamarti** [OHDSI/PhenotypeR#32]
phenotypeR it is very related to cohorts and codelist if we add also diagnostics of databases, I suggest to change the name of the package.

I never have good ideas but: omopDiagnostics? @edward-burn

**Comment by edward-burn** [comment]
@albertpratsu the package name is currently lower case (phenotypeR) wheras the hex sticker starts with a capital (PhenotypeR)

@albertpratsu you choose - what should the name be? (We have to choose before sending to cran because I can easily change it now but not once it is released there)
