### ISSUE TITLE
Show package versions

### ISSUE THREAD

**Issue by catalamarti** [OHDSI/phenotypeR#53]
https://darwin-eu-dev.github.io/omopgenerics/reference/resultPackageVersion.html

**Comment by edward-burn** [comment]
Not sure what you mean @catalamarti ?

**Comment by catalamarti** [comment]
that function (resultPackageVersion) can be helpful to summarise package versions.
Also summary = TRUE in exportStaticShinyApp provides a summary of the packages used and their versions.
Open to change any of them if that can be helpful

**Comment by edward-burn** [comment]
Ah, then this will be done by https://github.com/OHDSI/phenotypeR/issues/85
