### ISSUE TITLE
Current shinyDiagnostics doesnt work with issues regarding background 

### ISSUE THREAD

**Issue by xihang-chen** [OHDSI/phenotypeR#77]
After using phenotypeR::phenotypeDiagnostics and feeding the results into phenotypeR::shinyDiagnostics, it threw an error:

```
Error in `omopViewer::exportStaticApp()`:
✖ `background` is not logical.
! `background` must be a logical; with length = 1; it can not contain NA; it can not be
  NULL.
```

Tagging @catalamarti as we briefly discussed this already

**Comment by edward-burn** [comment]
@xihang-chen can you try with the current github version? https://github.com/OHDSI/phenotypeR/blob/540078e916c4f5dc3ecb24c1b98428917ac1b172/R/shinyDiagnostics.R#L19 background is currently commented out there

**Comment by edward-burn** [comment]
@xihang-chen can you try again, this should now also be fixed

**Comment by xihang-chen** [comment]
@edward-burn this has been resolved now! Thanks! closing this issue now
