### ISSUE TITLE
Age and sex group counts

### ISSUE THREAD

**Issue by albertpratsu** [OHDSI/phenotypeR#84]
One of the important diagnostics we do is look at age distribution. 
Right now I can only see we calculate summary measures, but it would be great if we have a 5y and sex  strata  counts and %  , so we can view it in an age pyramid. 
This is much more useful for diseases where the age onset may be multimodal.

**Comment by edward-burn** [comment]
Sure! We can add this to cohortDiagnostics using [summariseCohortCount(cohort, cohortId = NULL, strata = list())](https://darwin-eu-dev.github.io/CohortCharacteristics/reference/summariseCohortCount.html)

**Comment by edward-burn** [comment]
As discussed with @martaalcalde @albertpratsu - start by:
- add age groups to summariseCharacteristics https://github.com/OHDSI/phenotypeR/blob/26146adced7c4ffd1db83a4bb7e074d2c780b7a9/R/cohortDiagnostics.R#L24 (start using the same as for population diagnostics https://github.com/OHDSI/phenotypeR/blob/26146adced7c4ffd1db83a4bb7e074d2c780b7a9/R/populationDiagnostics.R#L28
- add density plot of age (see https://github.com/darwin-eu-dev/CohortCharacteristics/blob/4d1660e8a3dd3eb21b8d88913af024f55ab47ec6/R/summariseCohortTiming.R#L47 for example of how this can be done)

**Comment by martaalcalde** [comment]
Great, so just to check in, now cohortDiagnostics does:
- strata argument has been removed
- tableCharacteristics stratified by age_group (default) and sex (but not crossed strata)
- Age density stratified by sex (the overall group isn't included)

I also removed the cohortDiagnostics part of the vignette where the strata argument was explained.

Is this okey?
