### ISSUE TITLE
Check that age density results plot appear in the shiny

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/PhenotypeR#87]

**Comment by edward-burn** [comment]
![image](https://github.com/user-attachments/assets/8ed90555-3c00-4db7-99d9-6e3814ee8214)

**Comment by edward-burn** [comment]
@catalamarti what do you think would be the best way to show the results from https://github.com/OHDSI/PhenotypeR/blob/24363db9936f4dafb62b9f03fd3a217c0a55edbd/R/cohortDiagnostics.R#L72 in the shiny (ideally would be the plot .... )

**Comment by martaalcalde** [comment]
In which section of the shiny should the age distribution go @edward-burn?

**Comment by edward-burn** [comment]
@martaalcalde I think a second tab in cohort characteristics would be nice - what do you think?
